MV-Clouds/Buildertek

.forceignore
force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp

TKS-21 Complete --> @jayyymin18  @Nishitsuthar  @Krunal-MvClouds

Bug/tks 21 - Complete

---

force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp

hide buttons

---

force-app/main/default/aura/BT_LightningLookup/BT_LightningLookup.cmp
force-app/main/default/aura/BT_LightningLookup/BT_LightningLookupController.js
force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp

open issue on BT_lightningLookUp scroll isuue (onblur)

---

force-app/main/default/classes/bryntumGanttController.cls
force-app/main/default/lwc/gantt_component/data/launch-saas.js
force-app/main/default/lwc/gantt_component/gantt_component.css
force-app/main/default/lwc/gantt_component/gantt_component.js
force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
force-app/main/default/lwc/gantt_component/lib/GanttToolbar.js

Conflict pop up which gives user a option to solve a conflict in. gantt chart occurred after any changes.

Feature/CHB-77/ Conflict popup gnatt chart

---

force-app/main/default/classes/BudgetContractCreateHelper.cls

Bug/b UI l 3487(open issue)

---

force-app/main/default/aura/BT_NewChangeOrderOverride/BT_NewChangeOrderOverride.cmp

changed height for model, minor CSS changes

BT-1000-BUIL-3494-Change-Order-New-Change-Order-Modal-needs-to-be-taller

---

force-app/main/default/lwc/gantt_component/gantt_componentHelper.js

BT-998-BUIL-3492-New-Schedule-I-created-a-schedule-from-a-budget-and-it-did-so

---

force-app/main/default/aura/BT_NewChangeOrderOverride/BT_NewChangeOrderOverrideController.js

BT-999-BUIL-3495-Change-Order-Refreshing-the-Page-on-creation

---

force-app/main/default/classes/scheduleOfValueTriggerHandler.cls

Ticket Done. @jayyymin18  @Nishitsuthar  Please Merge this branch ASAP.

Feature/b UI l 3490

---

force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp
force-app/main/default/classes/ImportCsvQuoteController.cls

Solved the issue related to Import External Quote and removed the unwanted Buttons from Quote and Budget.

BT-1001-BUIL-3496-Need-to-fix-the-Import-External-Quotes-button-to-add-to-the-Name-field-and-the-Product-Description-field

---

force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemCloneController.js
force-app/main/default/aura/Preview_Billings/Preview_BillingsController.js
force-app/main/default/aura/Preview_Billings/Preview_BillingsHelper.js
force-app/main/default/classes/PreviewBillingsController.cls

Auto populating the TO field in the Sales Invoice Template and Open issues related to the Quote.

BT-1006-AC-44-BT-Invoice-Template-changes

---

force-app/main/default/aura/New_InvoicePO_Component/New_InvoicePO_Component.cmp
force-app/main/default/aura/New_InvoicePO_Component/New_InvoicePO_Component.css
force-app/main/default/aura/New_InvoicePO_Component/New_InvoicePO_ComponentController.js
force-app/main/default/aura/New_InvoicePO_Component/New_InvoicePO_ComponentHelper.js
force-app/main/default/classes/New_InvoicePO_ComponentFields.cls

When creating a Contractor Invoice (PO) from a Project it is not populating the Project field in the Contractor Invoice (PO) record page. The Purchase order field must be filtered on the basis of the Project field value selected in the New Contractor Invoice (PO).

BT-1021-BUIL-3505

---

force-app/main/default/classes/NewGanttChartTaskTriggerHandler.cls
force-app/main/default/classes/bryntumGanttController.cls
force-app/main/default/classes/importScheduleLineController.cls
force-app/main/default/lwc/createNewSchedule/createNewSchedule.html
force-app/main/default/lwc/createNewSchedule/createNewSchedule.js
force-app/main/default/lwc/gantt_component/gantt_component.js
force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
force-app/main/default/lwc/gantt_component/lib/GanttToolbar.js
force-app/main/default/lwc/importScheduleLine/importScheduleLine.js

fixed common bugs in new gantt chart

Bt 1019 fb 3 flight builders schedule

---

force-app/main/default/aura/Add_QuoteLine_In_Quote/Add_QuoteLine_In_QuoteHelper.js
force-app/main/default/aura/BT_LookUp/BT_LookUp.cmp
force-app/main/default/aura/BT_LookUp/BT_LookUpController.js
force-app/main/default/aura/BT_MassAddBudgetItem/BT_MassAddBudgetItem.cmp

The scroll bar CSS issue is solved

BT-1035-BUIL-3524

---

force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp

White space Removed from Budget Line table from newbutgetitemclone

Bug/b UI l 3515

---

force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.css
force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemCloneController.js
force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemCloneHelper.js
force-app/main/default/classes/BudgetDAO.cls

Added the Subgrouping functionality in Budget.

BT-1015-BUIL-3500

---

force-app/main/default/classes/ChangeOrderTriggerHandler.cls

BT-1062-BUIL-3553

---

force-app/main/default/aura/CheckInCustomRecordPage/CheckInCustomRecordPage.cmp
force-app/main/default/aura/CheckInCustomRecordPage/CheckInCustomRecordPage.css
force-app/main/default/aura/CheckInCustomRecordPage/CheckInCustomRecordPageController.js
force-app/main/default/aura/CheckInCustomRecordPage/CheckInCustomRecordPageHelper.js
force-app/main/default/aura/CreateNewCheckInBtn/CreateNewCheckInBtn.cmp
force-app/main/default/classes/CheckInCustomRecordPageController.cls
force-app/main/default/classes/Test_CheckInCustomRecordPageController.cls

Check-in New custom image preview in BT Org.

Open issue/check in

---

force-app/main/default/classes/ContentDocumentLinkHandler.cls

BT-1064-BUIL-3554-Sifton-Error-ContentDocumentLink-isssue

---

force-app/main/default/classes/PreviewQuoteController.cls

BT-1073-BUIL-3562

---

force-app/main/default/aura/ContinuationSheetItems/ContinuationSheetItems.cmp
force-app/main/default/aura/ContinuationSheetItems/ContinuationSheetItems.css

BT-1080-BUIL-3568

---

force-app/main/default/aura/ImportBudgetLines/ImportBudgetLines.cmp
force-app/main/default/aura/Preview_Quote/Preview_Quote.cmp
force-app/main/default/aura/Preview_Quote/Preview_Quote.css
force-app/main/default/aura/Preview_Quote/Preview_QuoteController.js
force-app/main/default/aura/Preview_Quote/Preview_QuoteHelper.js
force-app/main/default/classes/PreviewQuoteController.cls

BT-1083-BUIL-3576

---

force-app/main/default/lwc/gantt_component/lib/GanttToolbar.js

BT-1094 - BUIL-3584

---

force-app/main/default/aura/OrderPOFromProject/OrderPOFromProject.cmp
force-app/main/default/aura/OrderPOFromProject/OrderPOFromProject.css

BT-1089 - BUIL-3579

---

force-app/main/default/aura/btCloneProject/btCloneProject.cmp
force-app/main/default/aura/btCloneProject/btCloneProjectController.js

BT-1090 - BUIL-3580

---

force-app/main/default/classes/ConfirmationController.cls
force-app/main/default/pages/ConfirmationPage.page

BT-1092 <Changes related to PO.>

---

force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp
force-app/main/default/classes/PreviewQuoteController.cls

BT-1096 - BUIL-3585

---

force-app/main/default/aura/OrderPOFromProject/OrderPOFromProject.cmp
force-app/main/default/classes/NewQuoteComponentController.cls
force-app/main/default/classes/PreviewQuoteController.cls

Open issue and css issue

---

force-app/main/default/components/QuotelineswithGroupingName.component

Solved the Quote template CSS issues.

BT-1135-BUIL-3632

---

force-app/main/default/aura/CheckInCustomRecordPage/CheckInCustomRecordPage.cmp
force-app/main/default/aura/CreateNewCheckInBtn/CreateNewCheckInBtn.cmp
force-app/main/default/aura/CreateNewCheckInBtn/CreateNewCheckInBtnController.js
force-app/main/default/aura/CreateNewCheckInBtn/CreateNewCheckInBtnHelper.js

Added New Create New CheckIn's Button

BT-1132-BUIL-3614

---

force-app/main/default/classes/BudgetItemTriggerHandler.cls
force-app/main/default/triggers/BudgetItemTrigger.trigger

Inserting the CostCode field value from product to budget line on BeforeInsert.

BT-1117 -BUIL-3609

---

force-app/main/default/aura/BT_MassAddBudgetItem/BT_MassAddBudgetItem.cmp
force-app/main/default/aura/BT_MassAddBudgetItem/BT_MassAddBudgetItem.css
force-app/main/default/aura/BT_MassAddBudgetItem/BT_MassAddBudgetItemController.js
force-app/main/default/aura/BT_MassAddBudgetItem/BT_MassAddBudgetItemHelper.js
force-app/main/default/classes/MassAddBudgetItemController.cls

Populating the Vendor field and unit cost from products in the New Budget Lines Model.

BT-1116 - BUIL-3604

---

force-app/main/default/classes/QuotelineswithGroupingNameController.cls
force-app/main/default/components/QuotelineswithGroupingName.component

BT-1135-BUIL-3632 <Solved the empty field issue>

---

force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp
force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.css

Solved the Width CSS issue on Quote.

BT-1146-BUIL-3633

---

force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasic.auradoc
force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasic.cmp
force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasic.cmp-meta.xml
force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasic.css
force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasic.design
force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasic.svg
force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasicController.js
force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasicHelper.js
force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasicRenderer.js
force-app/main/default/classes/ImportTakeOffLinesBasic.cls
force-app/main/default/classes/ImportTakeOffLinesBasic.cls-meta.xml

BT-1104-BUIL-3593

---

force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp

Changed the Duplicate icon to the Open icon that will be used to Open the Quote Line record page from Quote.

BT-1147-BUIL-3637

---

force-app/main/default/classes/ImportCsvQuoteController.cls
force-app/main/default/classes/MassUpdateQuote.cls
force-app/main/default/classes/QuoteDAO.cls

Populating the Product Name Long Field

BT-1148-BUIL-3636

---

force-app/main/default/aura/CheckInCustomRecordPage/CheckInCustomRecordPage.cmp
force-app/main/default/aura/CheckInCustomRecordPage/CheckInCustomRecordPage.css
force-app/main/default/classes/CheckInCustomRecordPageController.cls

Check-in -- Created date column add in Our(BT) Dev Org

BT-1166-BUIL-3645-Check-Ins

---

force-app/main/default/lwc/gantt_component/gantt_component.js

Removed the undeclare function.

BT-1173-BUIL-3651

---

force-app/main/default/aura/OrderPOFromProject/OrderPOFromProjectController.js
force-app/main/default/aura/OrderPOFromProject/OrderPOFromProjectHelper.js
force-app/main/default/classes/OrderPOFromProjectController.cls

Removed the Hard code line and added template in order PO from Project

BT-1161-BUIL-3644

---

force-app/main/default/aura/New_Schedule_Override/New_Schedule_OverrideHelper.js
force-app/main/default/classes/BT_NewGanttChartCls.cls
force-app/main/default/classes/ImportMasterSchedules.cls
force-app/main/default/classes/NewGanttChartTaskTriggerHandler.cls
force-app/main/default/classes/bryntumGanttController.cls
force-app/main/default/classes/futureContoller.cls
force-app/main/default/lwc/gantt_component/gantt_component.css
force-app/main/default/lwc/gantt_component/gantt_component.js
force-app/main/default/lwc/gantt_component/gantt_componentHelper.js

Schedule original start and completion date updating on project and on schedule

Bt 1180 b UI l 3650 

---

force-app/main/default/lwc/importScheduleLine/importScheduleLine.js

The CSV file had an empty row and fixed the issue by cleaning it up in the code

BT-1185-FB-8-import-Sch-Issue

---

force-app/main/default/aura/ImportInspectionLines/ImportInspectionLines.auradoc
force-app/main/default/aura/ImportInspectionLines/ImportInspectionLines.cmp
force-app/main/default/aura/ImportInspectionLines/ImportInspectionLines.cmp-meta.xml
force-app/main/default/aura/ImportInspectionLines/ImportInspectionLines.css
force-app/main/default/aura/ImportInspectionLines/ImportInspectionLines.design
force-app/main/default/aura/ImportInspectionLines/ImportInspectionLines.svg
force-app/main/default/aura/ImportInspectionLines/ImportInspectionLinesController.js
force-app/main/default/aura/ImportInspectionLines/ImportInspectionLinesHelper.js
force-app/main/default/aura/ImportInspectionLines/ImportInspectionLinesRenderer.js
force-app/main/default/classes/ImportInspectionLineController.cls
force-app/main/default/classes/ImportInspectionLineController.cls-meta.xml

Added a new component to import inspection line.

BT-1179 - BUIL-3653

---

force-app/main/default/aura/ScheduleSummary/ScheduleSummary.auradoc
force-app/main/default/aura/ScheduleSummary/ScheduleSummary.cmp
force-app/main/default/aura/ScheduleSummary/ScheduleSummary.cmp-meta.xml
force-app/main/default/aura/ScheduleSummary/ScheduleSummary.css
force-app/main/default/aura/ScheduleSummary/ScheduleSummary.design
force-app/main/default/aura/ScheduleSummary/ScheduleSummary.svg
force-app/main/default/aura/ScheduleSummary/ScheduleSummaryController.js
force-app/main/default/aura/ScheduleSummary/ScheduleSummaryHelper.js
force-app/main/default/aura/ScheduleSummary/ScheduleSummaryRenderer.js
force-app/main/default/classes/ScheduleSummaryController.cls
force-app/main/default/classes/ScheduleSummaryController.cls-meta.xml

Removed the Contractor filter from the Schedule Summary.

BT-1182-BUIL-3655

---

force-app/main/default/aura/NewTakeOffComponent/NewTakeOffComponent.auradoc
force-app/main/default/aura/NewTakeOffComponent/NewTakeOffComponent.cmp
force-app/main/default/aura/NewTakeOffComponent/NewTakeOffComponent.cmp-meta.xml
force-app/main/default/aura/NewTakeOffComponent/NewTakeOffComponent.css
force-app/main/default/aura/NewTakeOffComponent/NewTakeOffComponent.design
force-app/main/default/aura/NewTakeOffComponent/NewTakeOffComponent.svg
force-app/main/default/aura/NewTakeOffComponent/NewTakeOffComponentController.js
force-app/main/default/aura/NewTakeOffComponent/NewTakeOffComponentHelper.js
force-app/main/default/aura/NewTakeOffComponent/NewTakeOffComponentRenderer.js
force-app/main/default/classes/NewTakeOffComponentController.cls
force-app/main/default/classes/NewTakeOffComponentController.cls-meta.xml

Added a New Custom page for Takeoff record create.

BT-1184-BUIL-3659

---

force-app/main/default/classes/ProjectTriggerHandler.cls
force-app/main/default/classes/bryntumGanttController.cls

commented the code in projectTrigger which was overwriting the ori dates on the project

BT-1180 BUIL-3650

---

force-app/main/default/aura/BT_CreateInspection/BT_CreateInspection.cmp
force-app/main/default/aura/BT_CreateInspection/BT_CreateInspectionController.js
force-app/main/default/aura/BT_CreateInspection/BT_CreateInspectionHelper.js

Solved the Checkbox issue on Next and Previous.

BT-1183-BUIL-3658

---

force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.css
force-app/main/default/classes/BudgetDAO.cls

Solved the Vendor issue and Button alignment issue.

BT-1190-BUIL-3663

---

force-app/main/default/classes/ChangeOrderTriggerHandler.cls
force-app/main/default/triggers/ChangeOrderTrigger.trigger

Change Order RollUp trigger field methods added on project

BT 1210 BUIL 3685

---

force-app/main/default/aura/syncVendors/syncVendorsHelper.js

BT-1205-BUIL-3667

---

force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp
force-app/main/default/classes/ContractTriggerHandler.cls
force-app/main/default/classes/PurchaseOrderTriggerHandler.cls

Solved the error related to clone project from the project object.

BT-1215-BUIL-3689

---

force-app/main/default/aura/ImportMasterPurchaseOrder/ImportMasterPurchaseOrder.cmp

Replace the output text with the output URL for the name field.

BT-1234-BUIL-3711

---

force-app/main/default/aura/importTakeOff/importTakeOffController.js
force-app/main/default/classes/importTakeoff.cls

Handling the error message for empty line.

BT-1242-BUIL-3721

---

force-app/main/default/classes/ImportMasterPurchaseOrderController.cls

Made changes as per Brian's requirement related to the Purchase Order

BT-1219-BUIL-3691

---

force-app/main/default/lwc/gantt_component/gantt_component.css
force-app/main/default/lwc/gantt_component/gantt_component.js
force-app/main/default/lwc/gantt_component/gantt_componentHelper.js

name column click to redirect feature

BT-1241-BUIL-3719

---

force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp

Solved the 0.00% showing issue in Costcode on Budget.

BT-1236-BUIL-3715

---

force-app/main/default/aura/BT_MassUpdateTakeOffLines/BT_MassUpdateTakeOffLines.cmp
force-app/main/default/aura/BT_MassUpdateTakeOffLines/BT_MassUpdateTakeOffLinesController.js
force-app/main/default/aura/BT_MassUpdateTakeOffLines/BT_MassUpdateTakeOffLinesHelper.js
force-app/main/default/classes/MassUpdateTakeOffLines.cls

Solved the auto-refresh issue on the Mass Update takeoff line

BT-1263-BUIL-3724

---

force-app/main/default/classes/ProjectTaskTriggerHandler.cls
force-app/main/default/classes/ScheduleTriggerHandler.cls
force-app/main/default/triggers/ProjectTaskTrigger.trigger
force-app/main/default/triggers/ScheduleRecTrigger.trigger
force-app/main/default/triggers/ScheduleRecTrigger.trigger-meta.xml

Auto-populating the project field on schedule items whenever the schedule's project field value changes.

BT-1259-BUIL-3740

---

force-app/main/default/aura/CreatePaymentForInvoiceAP/CreatePaymentForInvoiceAP.cmp
force-app/main/default/aura/CreatePaymentForInvoiceAP/CreatePaymentForInvoiceAPController.js

in fieldset set value for project field

BT-1271-BUIL-3748

---

force-app/main/default/aura/BT_CreateNewCashDisbursement/BT_CreateNewCashDisbursement.cmp
force-app/main/default/aura/BT_CreateNewCashDisbursement/BT_CreateNewCashDisbursementHelper.js
force-app/main/default/classes/BT_NewCashDisbursementController.cls

in fieldset set the value for the project field on the cmp

BT-1268-BUIL-3746

---

force-app/main/default/classes/InvoiceTrigger_HDL.cls

Populating the Total Receipts field on Project.

BT-1272-BUIL-3747

---

force-app/main/default/classes/CreateBudgetLineItemForTimeCard.cls
force-app/main/default/classes/TimeCardTriggerHandler.cls
force-app/main/default/classes/futureContoller.cls

TimecardTrigger Future method can not be called into another future method.
changed code into TimecardTriggerHandler, CreateBudgetLineItemForTimeCard, and futureContoller

BT-1278-Open-Issue-2nd-Jan-2024

---

force-app/main/default/classes/BudgetTriggerHandler.cls

Added an automation on Budget delete.

BT-1277-BUIL-3755

---

force-app/main/default/aura/Preview_Quote/Preview_QuoteController.js
force-app/main/default/aura/Preview_Quote/Preview_QuoteHelper.js
force-app/main/default/classes/PreviewQuoteController.cls

Sending text body with Accept and Send Email functionality on Quote Preview model.

BT-1288-BUIL-3759

---

force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp

CSS changes on Quote and Budget.

BT-1287-BUIL-3764

---

force-app/main/default/aura/ImportMasterPurchaseOrder/ImportMasterPurchaseOrderController.js
force-app/main/default/aura/ImportMasterWalkThrough/ImportMasterWalkThroughController.js
force-app/main/default/aura/ImportPurchaseOrderFromBudget/ImportPurchaseOrderFromBudget.cmp
force-app/main/default/aura/ImportPurchaseOrderFromBudget/ImportPurchaseOrderFromBudget.css
force-app/main/default/aura/ImportPurchaseOrderFromBudget/ImportPurchaseOrderFromBudgetController.js

BT-1289-BUIL-3762

---

force-app/main/default/pages/BT_GenerateQuotePDF.page

Added some CSS properties to Quote PDF Generator.

BT-1293-BUIL-3767

---

force-app/main/default/classes/InvoiceTrigger_HDL.cls
force-app/main/default/triggers/invoiceTrigger.trigger

Update the status of the Sales Invoice to Open when all receipts related to the Sales Invoice get deleted.

BT-1294-BUIL-3769

---

force-app/main/default/aura/ContinuationDetails/ContinuationDetailsController.js
force-app/main/default/classes/ContinuationSheetLineTriggerHandler.cls
force-app/main/default/classes/CreatePaymentApplicationForBudget.cls
force-app/main/default/classes/scheduleOfValueTriggerHandler.cls

Added new functionality to update the status to Customer Approved once all Continuation Sheetline Approved.

BT-1302-BUIL-3778

---

force-app/main/default/aura/ImportSOVLineToPurchaseOrder/ImportSOVLineToPurchaseOrder.auradoc
force-app/main/default/aura/ImportSOVLineToPurchaseOrder/ImportSOVLineToPurchaseOrder.cmp
force-app/main/default/aura/ImportSOVLineToPurchaseOrder/ImportSOVLineToPurchaseOrder.cmp-meta.xml
force-app/main/default/aura/ImportSOVLineToPurchaseOrder/ImportSOVLineToPurchaseOrder.css
force-app/main/default/aura/ImportSOVLineToPurchaseOrder/ImportSOVLineToPurchaseOrder.design
force-app/main/default/aura/ImportSOVLineToPurchaseOrder/ImportSOVLineToPurchaseOrder.svg
force-app/main/default/aura/ImportSOVLineToPurchaseOrder/ImportSOVLineToPurchaseOrderController.js
force-app/main/default/aura/ImportSOVLineToPurchaseOrder/ImportSOVLineToPurchaseOrderHelper.js
force-app/main/default/aura/ImportSOVLineToPurchaseOrder/ImportSOVLineToPurchaseOrderRenderer.js
force-app/main/default/aura/NewTakeOffComponent/NewTakeOffComponent.cmp
force-app/main/default/classes/ImportSOVLineToPOController.cls
force-app/main/default/classes/ImportSOVLineToPOController.cls-meta.xml

Created a new button to Import SOV Lines on Purchase Orders.

BT-1306-BUIL-3780

---

force-app/main/default/aura/Post_to_QuickBook/Post_to_QuickBook.cmp
force-app/main/default/aura/Post_to_QuickBook/Post_to_QuickBookController.js
force-app/main/default/aura/Post_to_QuickBook/Post_to_QuickBookHelper.js
force-app/main/default/classes/QBIntegrationQueue.cls
force-app/main/default/classes/QBIntegrationQueue_SIFlow.cls
force-app/main/default/classes/QBMap.cls
force-app/main/default/classes/QBReceiptResponseJSON.cls

Quickbook Integration

---

force-app/main/default/aura/Invoice_From_PaymentApp/Invoice_From_PaymentApp.cmp
force-app/main/default/aura/Invoice_From_PaymentApp/Invoice_From_PaymentAppController.js
force-app/main/default/classes/Invoice_From_PaymentApp.cls

Here commented code is for creating payable invoice which brian asked to comment the code and instead create contractor invoice

BT-1308-BUIL-3784

---

force-app/main/default/aura/BT_RFQ_Review_Compare/BT_RFQ_Review_Compare.cmp

Made some css changes and added a new field named as Vendor Note on RFQ.

BT-1313-BUIL-3791

---

force-app/main/default/classes/PurchaseOrderTriggerHandler.cls

Autopopulating the inventory status on PO based on Remaining and Received fields.

BT-1336-BUIL-3819

---

force-app/main/default/aura/BT_Import_Master_Quote/BT_Import_Master_Quote.cmp
force-app/main/default/classes/BudgetTriggerHandler.cls
force-app/main/default/classes/ContactTriggerHandler.cls
force-app/main/default/classes/ContactTriggerHandler.cls-meta.xml
force-app/main/default/classes/ContactTriggerHandlerTest.cls
force-app/main/default/classes/ContactTriggerHandlerTest.cls-meta.xml
force-app/main/default/classes/TimeCardTriggerHandler.cls
force-app/main/default/triggers/BudgetTrigger.trigger
force-app/main/default/triggers/ContactTrigger.trigger
force-app/main/default/triggers/ContactTrigger.trigger-meta.xml
force-app/main/default/triggers/TimecardTrigger.trigger

Solved the flow and process builder issue-related to heiler production org.

BT-1348-BUIL-3828

---

force-app/main/default/aura/BT_CreateReceivable/BT_CreateReceivable.cmp
force-app/main/default/aura/BT_CreateReceivable/BT_CreateReceivable.css
force-app/main/default/aura/CreatePOFromCO/CreatePOFromCO.cmp
force-app/main/default/aura/CreatePOFromCO/CreatePOFromCOController.js
force-app/main/default/aura/CreatePOFromCO/CreatePOFromCOHelper.js
force-app/main/default/aura/ImportPOinCO/ImportPOinCO.cmp
force-app/main/default/aura/ImportPOinCO/ImportPOinCO.css

Solved message not showing with spinner

BT-1330-BUIL-3813

---

force-app/main/default/classes/QuoteDAO.cls

Solved the product family sorting issue.

BT-1355-BUIL-3841

---

force-app/main/default/aura/BT_CreatePayables/BT_CreatePayablesController.js
force-app/main/default/aura/BT_CreatePayables/BT_CreatePayablesHelper.js

Solve the create contractor issue from PO in flight builder org.

BT-1354-BUIL-3837

---

force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasic.cmp
force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasicHelper.js
force-app/main/default/classes/ImportTakeOffLinesBasic.cls

Added a new field and replaced category to the Import Takeoff Lines Basic Component.

BT-1374-BUIL-3864

---

force-app/main/default/classes/BT_CreateBOMfromTakeoffController.cls

Added a new logic for the vendor in Create BOM from takeoff.

BT-1387-BUIL-3873

---

force-app/main/default/classes/ContractTriggerHandler.cls
force-app/main/default/triggers/ContractTrigger.trigger

Replace the field of contract to populate the contract amount field on Project.

BT-1398-BUIL-3885

---

force-app/main/default/classes/TimeCardTriggerHandler.cls

Added a new field in the automation of time card to populate the total hour field on the project.

BT-1397-BUI-3884

---

force-app/main/default/aura/BT_ReceiveMaterial/BT_ReceiveMaterial.cmp
force-app/main/default/aura/BT_ReceiveMaterial/BT_ReceiveMaterialController.js
force-app/main/default/aura/BT_ReceiveMaterialPOLines/BT_ReceiveMaterialPOLines.cmp
force-app/main/default/aura/BT_ReceiveMaterialPOLines/BT_ReceiveMaterialPOLinesController.js

BT-1388 BUIL-3879/80

---

force-app/main/default/aura/BT_ImportSelectionSheet/BT_ImportSelectionSheet.cmp
force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.css
force-app/main/default/aura/ImportMasterProjectTakeoff/ImportMasterProjectTakeoff.cmp
force-app/main/default/aura/ImportPurchaseOrderFromBudget/ImportPurchaseOrderFromBudgetController.js
force-app/main/default/aura/Select_Quote_To_Import/Select_Quote_To_Import.cmp
force-app/main/default/classes/BudgetDAO.cls
force-app/main/default/classes/CO_From_Selection_Category.cls
force-app/main/default/classes/ImportMasterProjectTakeoff.cls
force-app/main/default/classes/ImportMasterSchedules.cls
force-app/main/default/classes/ImportSelectionSheet.cls
force-app/main/default/classes/ImportSubContractorForBudgetController.cls
force-app/main/default/classes/ImportmasterBudgetClass.cls
force-app/main/default/classes/ManageBOMlinesController.cls
force-app/main/default/classes/PO_From_Selection_Sheet.cls
force-app/main/default/classes/RFQDAO.cls
force-app/main/default/classes/createCO_selectionType.cls
force-app/main/default/classes/createRFQClass.cls
force-app/main/default/classes/importTakeoff.cls

Added sorting functionality on all import models for Budget, Quotes, Takeoffs, Schedule, Selection, and BOM objects.

BT-1399-BUIL-3889

---

force-app/main/default/aura/New_InvoicePO_Component/New_InvoicePO_Component.cmp
force-app/main/default/aura/SchedulePO/SchedulePO.cmp
force-app/main/default/aura/SchedulePO/SchedulePO.css
force-app/main/default/aura/SchedulePO/SchedulePOController.js
force-app/main/default/aura/SchedulePO/SchedulePOHelper.js
force-app/main/default/classes/SchedulePOController.cls

Redesigned the whole New Task component on PO that will used to insert Task on Schedule.

BT-1405-BUIL-3896

---

force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemCloneHelper.js

Added summary fields for five more fields for all budget lines on the Budget record page.

BT-1412-BUIL-3910

---

force-app/main/default/aura/Import_Products_On_RfqLines/Import_Products_On_RfqLinesHelper.js
force-app/main/default/classes/ImportMasterProjectTakeoffTest.cls
force-app/main/default/classes/ImportMasterPunchLineTest.cls
force-app/main/default/classes/ImportMasterQuotesTest.cls
force-app/main/default/classes/ImportMasterSchedulesTest.cls
force-app/main/default/classes/ImportmasterBudgetClassTest.cls
force-app/main/default/classes/ImportmasterInspectionClassTest.cls

Solved cancel button issues and class issues.

BT-1416-BUIL-3918

---

force-app/main/default/aura/BT_ImportMasterToDo/BT_ImportMasterToDo.cmp
force-app/main/default/aura/BT_ImportMasterToDo/BT_ImportMasterToDoController.js
force-app/main/default/aura/BT_ImportMasterToDo/BT_ImportMasterToDoHelper.js
force-app/main/default/classes/ImportMasterToDo.cls

Redesigned the master import todo component.

BT-1420-BUIL-3919

---

force-app/main/default/lwc/gantt_component/gantt_component.css
force-app/main/default/lwc/gantt_component/gantt_component.js
force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
force-app/main/default/lwc/gantt_component/lib/BryntumGanttIcons.js
force-app/main/default/lwc/gantt_component/lib/GanttToolbar.js

BUIL-3906
BUIL-3912,
BUIL-3913,

BT-1427 BUIL-3913 Schedule changes

---

force-app/main/default/classes/BT_FileSharingControllerTest.cls
force-app/main/default/classes/ImportMasterToDoTest.cls

TestClass Issues

---

force-app/main/default/lwc/gantt_component/gantt_component.js
force-app/main/default/lwc/gantt_component/lib/GanttToolbar.js

Rename a button and change the predecessor column placed in the schedule Gantt chart.

BT-1435-BUIL-3930

---

force-app/main/default/aura/PrintQuoteInformation/PrintQuoteInformation.cmp
force-app/main/default/aura/PrintQuoteInformation/PrintQuoteInformationController.js
force-app/main/default/aura/PrintQuoteInformation/PrintQuoteInformationHelper.js

Added functionality to choose a quote template if there are multiple quote templates on the Print Quote model.

BT-1447-BUIL-3945

---

force-app/main/default/classes/BT_SendRFQEmailController.cls

Changed the sender's email address.

BT-1451-BUIL-3948

---

force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.auradoc
force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.cmp
force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.cmp-meta.xml
force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.css
force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.design
force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.svg
force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformationController.js
force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformationHelper.js
force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformationRenderer.js
force-app/main/default/classes/PreviewBillingsController.cls

Created a new component to print sales invoices on the Sales Invoice record page.

BT-1463-BUIL-3957

---

force-app/main/default/lwc/gantt_component/gantt_component.js
force-app/main/default/lwc/gantt_component/gantt_componentHelper.js

While importing master not copying the internal resource in the newly created schedule - fixed the issue
along with another issue which I caught where red color feature was not working properly - fixed the issue

BT-1466 Not Copying Resource

---

force-app/main/default/aura/AddProductsToPurchaseOrder/AddProductsToPurchaseOrder.cmp
force-app/main/default/aura/AddProductsToPurchaseOrder/AddProductsToPurchaseOrderController.js
force-app/main/default/aura/AddProductsToPurchaseOrder/AddProductsToPurchaseOrderHelper.js
force-app/main/default/classes/AddProductsToPurchaseOrder.cls

Solved CSS and filtration issues on the Add Product component.

BT-1464-BUIL-3962

---

force-app/main/default/classes/AccountPayableHelper.cls
force-app/main/default/classes/AddBudgetLineItemOnPayableInvoice.cls
force-app/main/default/classes/BudgetDAO.cls

Changes the name of the budget line created from AP and PO.

BT-1470-BUIL-3966

---

force-app/main/default/classes/RequestInvoiceFromPOController.cls

Removed the signature from the email template and added in code.

BT-1471-BUIL-3969

---

force-app/main/default/aura/BT_CreateQuoteFromOpportunity/BT_CreateQuoteFromOpportunity.cmp
force-app/main/default/aura/BT_CreateQuoteFromOpportunity/BT_CreateQuoteFromOpportunityController.js
force-app/main/default/classes/QuoteController.cls

Solved the name issue for the quote line.

IBT-1450-BUIL-3973

---

force-app/main/default/aura/RequestInvoiceFromPOWithActualQuantity/RequestInvoiceFromPOWithActualQuantity.auradoc
force-app/main/default/aura/RequestInvoiceFromPOWithActualQuantity/RequestInvoiceFromPOWithActualQuantity.cmp
force-app/main/default/aura/RequestInvoiceFromPOWithActualQuantity/RequestInvoiceFromPOWithActualQuantity.cmp-meta.xml
force-app/main/default/aura/RequestInvoiceFromPOWithActualQuantity/RequestInvoiceFromPOWithActualQuantity.css
force-app/main/default/aura/RequestInvoiceFromPOWithActualQuantity/RequestInvoiceFromPOWithActualQuantity.design
force-app/main/default/aura/RequestInvoiceFromPOWithActualQuantity/RequestInvoiceFromPOWithActualQuantity.svg
force-app/main/default/aura/RequestInvoiceFromPOWithActualQuantity/RequestInvoiceFromPOWithActualQuantityController.js
force-app/main/default/aura/RequestInvoiceFromPOWithActualQuantity/RequestInvoiceFromPOWithActualQuantityHelper.js
force-app/main/default/aura/RequestInvoiceFromPOWithActualQuantity/RequestInvoiceFromPOWithActualQuantityRenderer.js
force-app/main/default/classes/RequestInvoiceFromPOController.cls
force-app/main/default/classes/RequestInvoicePageForAQ.cls
force-app/main/default/classes/RequestInvoicePageForAQ.cls-meta.xml
force-app/main/default/pages/RequestInvoicePageForActualQuantity.page
force-app/main/default/pages/RequestInvoicePageForActualQuantity.page-meta.xml

Added a new vf page to add actual quantity in it.

IBT-1002-BUIL-3970

---

force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasic.cmp
force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasicHelper.js
force-app/main/default/aura/ImportMasterProjectTakeoff/ImportMasterProjectTakeoff.cmp
force-app/main/default/classes/ImportMasterProjectTakeoff.cls
force-app/main/default/classes/ImportTakeOffLinesBasic.cls

Added tax fields in import models of takeoffs

IBT-1466-BUIL-3995

---

force-app/main/default/aura/BT_AddExistingBudget/BT_AddExistingBudget.cmp
force-app/main/default/aura/BT_AddExistingBudget/BT_AddExistingBudgetHelper.js
force-app/main/default/classes/AddExistingBudgetController.cls
force-app/main/default/classes/AddExistingBudgetControllerTest.cls
force-app/main/default/classes/createBudgetlineitemForTimeCard_AC.cls

Solved the bugs found in FEI org.

IBT-1458-BUIL-3993

---

force-app/main/default/classes/AccountPayableHelper.cls
force-app/main/default/classes/AddBudgetLineItemOnPayableInvoice.cls
force-app/main/default/classes/InvoiceAPTriggerHandler.cls
force-app/main/default/classes/InvoiceTrigger_HDL.cls
force-app/main/default/classes/PurchaseOrderTriggerHandler.cls
force-app/main/default/triggers/PurchaseOrderTrigger.trigger

Added some logic to delete the budget lines on budget.

IBT-1471-BUIL-3989

---

force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemCloneController.js
force-app/main/default/classes/BudgetDAO.cls

Added Payable Invoice functionality to Contractor Invoice button.

IBT-1467-BUIL-3983

---

force-app/main/default/aura/OrderPOFromProject/OrderPOFromProject.cmp
force-app/main/default/aura/OrderPOFromProject/OrderPOFromProjectController.js
force-app/main/default/aura/OrderPOFromProject/OrderPOFromProjectHelper.js

added the delete button and fixed one bug found during the unit testing

Ibt 1475 b UI l 4001

---

force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.auradoc
force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.cmp
force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.cmp-meta.xml
force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.css
force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.design
force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.svg
force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_ReviewsController.js
force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_ReviewsHelper.js
force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_ReviewsRenderer.js
force-app/main/default/classes/ImportMasterReviews.cls
force-app/main/default/classes/ImportMasterReviews.cls-meta.xml
force-app/main/default/classes/ImportMasterReviewsTest.cls
force-app/main/default/classes/ImportMasterReviewsTest.cls-meta.xml

fixed on CSS bug reported by Dhruv

Bt 1475 b UI l 4019

---

force-app/main/default/classes/createSinglePOsController.cls

IBT-1513 added condition to check for duplicate

---

force-app/main/default/aura/BT_FieldSetMassUpdate/BT_FieldSetMassUpdate.cmp
force-app/main/default/aura/BT_FieldSetMassUpdate/BT_FieldSetMassUpdateController.js
force-app/main/default/aura/BT_LightningLookup/BT_LightningLookup.cmp
force-app/main/default/aura/BT_LightningLookup/BT_LightningLookupController.js
force-app/main/default/aura/BT_LightningLookupEvent/BT_LightningLookupEvent.evt
force-app/main/default/aura/BT_LightningLookupResult/BT_LightningLookupResult.cmp
force-app/main/default/aura/BT_LightningLookupResult/BT_LightningLookupResultController.js
force-app/main/default/aura/BT_LookupEvent/BT_LookupEvent.evt
force-app/main/default/aura/BT_LookupFields/BT_LookupFieldsController.js
force-app/main/default/aura/BT_ManageBOMLines/BT_ManageBOMLines.cmp
force-app/main/default/aura/BT_ManageBOMLines/BT_ManageBOMLinesController.js
force-app/main/default/aura/BT_ManageBOMLines/BT_ManageBOMLinesHelper.js
force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOM.cmp
force-app/main/default/classes/FieldsetUtilityClass.cls
force-app/main/default/classes/ManageBOMlinesController.cls

optimization of the mass update BOM line controller and updated child component with new params in events for inner grouping index

Ibt 1537 b UI l 4062

---

force-app/main/default/aura/BT_LightningLookup/BT_LightningLookup.cmp
force-app/main/default/aura/BT_LightningLookup/BT_LightningLookupController.js
force-app/main/default/aura/BT_MassAddBudgetItem/BT_MassAddBudgetItem.cmp

fixed product selection bug on mass add budget line component

Ibt 1573 b UI l 4108

---

force-app/main/default/classes/PurchaseOrderTriggerHandler.cls
force-app/main/default/classes/createVoidPOController.cls

additional logic in void po button

Ibt 1664 b UI l 4167

---

force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemCloneController.js
force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemCloneHelper.js
force-app/main/default/classes/QuoteDAO.cls
force-app/main/default/classes/QuoteItemTriggerHandler.cls

solve the issue of creating double quote line

Ibt 1677 b UI l 4176

---

force-app/main/default/aura/ChecklistForm/ChecklistForm.cmp
force-app/main/default/aura/ChecklistForm/ChecklistFormController.js
force-app/main/default/aura/ChecklistForm/ChecklistFormHelper.js
force-app/main/default/classes/checkListQuestionsCtrl.cls

Grouping logic for checklist form

Ibt 1691 b UI l 4159 sub task 3

---

force-app/main/default/classes/CreateProjectfromQuoteAcceptanceonOpp.cls
force-app/main/default/classes/QuotelineswithGroupingNameController.cls
force-app/main/default/components/QuotelineswithGroupingName.component
force-app/main/default/pages/CreateProjectfromQuoteAcceptanceonOpp.page

…ed that in preview quote grouping component

IBT-1754-BUIL-4239
